### ISSUE TITLE
Switching variety when buying product doesn't change selected size

### ISSUE THREAD

**Issue by aabounegm** [Innopoints/frontend#154]
When buying a product and having selected a color/size as such:
![image](https://user-images.githubusercontent.com/11016151/77859734-c3043780-7213-11ea-81f4-5ef3c1c26ad6.png)
Then switching to another color without selecting a different size (or trying to click the same selected chip) keeps the previously selected size:
![image](https://user-images.githubusercontent.com/11016151/77859764-dca57f00-7213-11ea-858a-100819ad46cb.png)
And when clicking "buy", the size from the previously selected color remains selected:
![image](https://user-images.githubusercontent.com/11016151/77859774-f21aa900-7213-11ea-950a-f29a96e49f84.png)

**Comment by illright** [comment]
How do you wanna go around this? I see four implementations:
1. Change it to the first available size of the newly selected color
Could be bad if the person only wanted to switch the color and didn't notice that the size also changed

2. Leave it as it is
More likely for the person to notice that something's wrong since they'll see a different color in the purchase popup

3. Change it to the same size, if it exists, select the first available size otherwise

3. Change it to the same size, if it exists, leave it as it is otherwise
These two sound good at first, but those ifs create unpredictability, which isn't good

**Comment by aabounegm** [comment]
I disagree with the second point. Even if someone notices the problem in the popup, they are highly likely to close it and just try clicking the chip of the size they want and get angry when it still doesn't change, unaware that they need to press another chip first to trigger the `change` or `input` event.
I think the better option would be:

5. Change it to the same if it exists, `null` otherwise (hence disabling the "purchase" button) so the user notices for sure that the previously selected size is not available in this color
